//
//  RequestMacro.swift
//  Networking
//
//  Created by Joe Maghzal on 2/12/25.
//

import Foundation

/// Macro for defining a request structure that conforms to ``Request``.
///
/// This macro simplifies the process of defining a request by automatically
/// adding necessary properties and conformances.
/// It automatically adds the requirements needed to conform to ``Request``.
///
/// ```
/// @Request
/// struct FetchUserRequest {
///     var request: some Request {
///         // ...
///     }
/// }
/// ```
///
/// You can specify a custom request ID or use the default value which is the name of the request:
/// ```
/// @Request("fetchUser")
/// struct FetchUserRequest {
///     var request: some Request {
///         // ...
///     }
/// }
/// ```
///
/// You can also specify a variable request ID to override the one generated by the macro:
/// ```
/// @Request
/// struct FetchUserRequest {
///     var id = "" // Can be changed at run time.
///     var request: some Request {
///         // ...
///     }
/// }
/// ```
///
/// - Parameter id: An optional unique identifier for the request.
///
/// - Note: This macros is needed for the ``Header`` & ``Parameter``
/// macros to work.
@attached(extension, conformances: Request, _ModifiableRequest)
@attached(member, conformances: Request, names: named(modifier), named(id), named(_accept))
public macro Request(_ id: String = "") = #externalMacro(
    module: "NetworkingCoreMacros",
    type: "RequestMacro"
)

// TODO: - Add support for mods builder in init for composable requests

@attached(extension, conformances: RequestModifier)
@attached(member, conformances: RequestModifier, names: named(_accept))
public macro RequestModifier() = #externalMacro(
    module: "NetworkingCoreMacros",
    type: "RequestModifierMacro"
)
